### ISSUE TITLE
도메인 변경작업

### ISSUE THREAD

**Issue by drakejin** [pickstudio/infrastructure#16]
### slack

https://pickstudio2018.slack.com/archives/C018WPVGHDJ/p1606029369003900

### 대충 요약

WIX에서 fitca 도메인 연결 된 것(www.pickstudio.com) 에서 (fitca.pickstudio.com)으로 변경 해야합니다

**Comment by drakejin** [comment]
wix 도메인 변경작업하는데 거의 반나절임.. 천천히 해도 괜찮을듯

**Comment by xadparo** [comment]
route53에서 레코드 추가는 했는데 반영이 좀 걸리네요, 붙는거 확인하고 또 공유하겠습니다

**Comment by drakejin** [comment]
오오 route53에는 A레코드? CNAME? 어떻게 넣었어요?!  엄청 좋네요 ㅋㅋ크크

**Comment by xadparo** [comment]
![image](https://user-images.githubusercontent.com/45482148/100029493-c9938f00-2e34-11eb-901a-f9f32ecad9fa.png)

지금 다시 확인해보니깐, 아직 연결이 안되있네요 ㅋㅋㅋ 48시간의 기다림을 갖겠습니다

**Comment by xadparo** [comment]
> 오오 route53에는 A레코드? CNAME? 어떻게 넣었어요?! 엄청 좋네요 ㅋㅋ크크

ㅋㅋㅋ ㄹㅇ루다가 편리합니다

**Comment by xadparo** [comment]
https://fitca.pickstudio.io/
완료!
