### ISSUE TITLE
각 팀별 ECR생성을 위해 repo 현황 파악 하기

### ISSUE THREAD

**Issue by drakejin** [pickstudio/infrastructure#17]
# 개요
- ECS 에 deploy할 서비스들의 dockerize를 저장할 AWS ECR repository 개설하기

# 작업설명
각 서비스팀 별로 ECR을 필요로하는 프로젝트 현황파악하기
- picka
- pickma
- buddy stock

# 목표 작업 결과물

- wiki 페이지에 ECR 현황도큐먼트 만들기
- ECR 프로젝트 만들기
- 각 팀별 사용리소스 정리하기

**Comment by drakejin** [comment]
Example

# 어플리케이션 정보

- 어플리케이션 이름: birdystock-api
- 팀 이름: birdystock
- sidecar container (함께 떠 올라야하는 container)
    - logstash 
    - nginx

#### 환경변수
- 사용해야하는 환경변수 정보
- (환경변수를 쓰지않고 파일로 관리되는 프로젝트라면, 어떻게 관리되는지 전략을 알려주면 좋음)

#### 필요 외부 리소스

- mysql
- redis
- AWS S3
- AWS SQS

**Comment by pan-dugongman** [comment]
@drakejin 

# 어플리케이션 정보
ECR : 755991664675.dkr.ecr.ap-northeast-2.amazonaws.com/pickpublic-chat
git : 빠른 시일 내 아래 두 프로젝트를 결합하여 정리 예정
- https://github.com/pickstudio/pickme-chat
- https://github.com/pickstudio/birdiebuddy-api

어플리케이션 이름: pickpublic-chat
팀 이름: pickpublic

sidecar container (함께 떠 올라야하는 container)
  - redis
  - push noti service[미정]

  
## 환경변수
미정입니다
- ~~사용해야하는 환경변수 정보~~
- ~~(환경변수를 쓰지않고 파일로 관리되는 프로젝트라면, 어떻게 관리되는지 전략을 알려주면 좋음)~~

필요 외부 리소스
- dynamoDB [논의중]
- 위 사이드 컨테이너로 레디스랑 push noti (ex SQS)를 올릴지 고민

**Comment by pan-dugongman** [comment]
@drakejin 

# 어플리케이션 정보
ECR : 755991664675.dkr.ecr.ap-northeast-2.amazonaws.com/pickme-next-api
git : https://github.com/pickstudio/pickme-next-api (어떤 이슈로 주소가 바뀌었다고 하여 정정 필요)

어플리케이션 이름: pickme-match
팀 이름: pickme

sidecar container (함께 떠 올라야하는 container)
  - mongoDB

  
## 환경변수
파악 필요
- ~~사용해야하는 환경변수 정보~~
- ~~(환경변수를 쓰지않고 파일로 관리되는 프로젝트라면, 어떻게 관리되는지 전략을 알려주면 좋음)~~

필요 외부 리소스
- 위 사이드 컨테이너로 mongoDB를 올릴지 제품으로 올릴지 고민

**Comment by drakejin** [comment]
주문하신 mongodb 나왔습니다. 
 호스트 정보는 dm을 통해 드리도록 하겠습니다~
