### ISSUE TITLE
팀별 서비스별로 원하는 인프라 조사

### ISSUE THREAD

**Issue by drakejin** [pickstudio/infrastructure#20]
# 각 팀별 원하는 인프라 조사

### picka
- ?

### pickme

[참고 docker-compose](https://github.com/pickstudio/infrastructure/blob/main/remote_ec2/pickme/docker-compose.yml)

- mongodb
    - HOST: playground.development.pickstudio.io:27017
    - USERNAME: username
    - PASSWORD: password

- mongodb-express
    - HOST: playground.development.pickstudio.io:28081

- redis
    - HOST: playground.development.pickstudio.io:26379
        
### buddystock

[참고 docker-compose](https://github.com/pickstudio/infrastructure/blob/main/remote_ec2/buddystock/docker-compose.yml)

- redis
    - HOST: playground.development.pickstudio.io:16379

### 다익스트라

**Comment by pan-dugongman** [comment]
pickme - mongoDB

**Comment by drakejin** [comment]
https://github.com/pickstudio/infrastructure/issues/17

요기도 같이 채워주면 좋을거 같은디..!
